c demo input for vis3d_export_demo
c @VIS3D BEGIN
c @VIS3D MODE=SURFACE
c @VIS3D FORMAT=VTP
c @VIS3D OUTPUT=sample_mcnp.vtp
c @VIS3D AUTO_BBOX=YES
c @VIS3D FIELDS=CELL_ID,MATERIAL_ID,UNIVERSE_ID,SURFACE_ID
c @VIS3D COLORBY=CELL_ID
c @VIS3D END
