# demo input for vis3d_export_demo
# @VIS3D BEGIN
# @VIS3D MODE=VOXEL
# @VIS3D FORMAT=VTI
# @VIS3D OUTPUT=sample_mcx.vti
# @VIS3D AUTO_BBOX=YES
# @VIS3D DIM=24,16,12
# @VIS3D FIELDS=CELL_ID,MATERIAL_ID,UNIVERSE_ID,LATTICE_ID,INSTANCE_ID
# @VIS3D COLORBY=MATERIAL_ID
# @VIS3D END
